dist: trusty
sudo: required
services:
- docker
before_install:
- pip install --upgrade awscli
script:
- "make docker-cross
  && cd tests
  && ./run-tests.sh
  && aws s3 sync
    --metadata Version=$(git describe --long --tags --dirty --always),TravisJobNumber=${TRAVIS_JOB_NUMBER}
    --acl public-read
    ../build_docker_cross/
    s3://biscuit-binaries/$(git symbolic-ref --short HEAD)/latest/"
env:
  global:
  - secure: goNhQbKr0NfJ1k1Od+aDav6f/f7pwcSPZLIGiEYeuTpE4wUSG8GoYINpzFzCZi/ermEqdN5Be8h1grhWJ5TcbyQrh5NY/ZgMI0QgljZH1lW5dwYA88hSnsuMkg8BV5Ky8gvIh18v+Vqx9a4+ACT36is5YINJwBxE6UFAo8a1YVmlhddcRc+TVcKpzPzmalaul4PwN7zUvJbSJiJk7/eAmNB6k3XcSfM+MdmJ8YietcSXMDiWu4QcD4sEeceUPrjStH2mlcQRfwlG18cMGEThURu3B0PWoZvLw/0JlEp538PYPKMawxWgEFpqJhCmxdBnLM7jJi7L2Qfl/7HBJyXVyAqJ/cxztl1PXSsLjnrIHKSZAzeKvVqpSb5vqaZNwq4SNv+cSdIv89f+lmvNt4d2mNzGlmysw/1qwgCjjIoGtf8BnUF4bSQtwvYbZLHg80fvfKFKMNOatMzkU7ZrAlpjSQ7AV9EpQECk9mu8WQ7x5LLyw/DtJRhoyVj+dnlwKWrfhYho6hN7k+lip0L3dDtp/4p5zJMCjgIi2jdmabjtyGRRlHhsuNXlNFRl8EWFykrzKHvtZbrHq+DCkgG0vKo8xQTAZKBEfy/N/GSpHOTEqsl9UVhnj+0Y9e5ScpukYOLGJu6fdPLVvhh2iGTq4y+n8TMvHDdDGU4n81TKHdKsln4=
  - secure: dLwhpvLNBNMI49IBMp7lp8gwTef1DD4BFaCju9F4WzR85fA0Ut1PJfje5huyjrOyHR4YAilQ0cCPYGAmvyFQyGSIoyfkz2OAj3kwzka3xb5raDyA5jwdNmikbnJ0IhCrIi3rYwoka7awqnVJum4lYMYBEfbOePOEg9GkzEpYSIHjapDwngVnPWAokdHtOgmcLSy7Bg5V5iFYdREWBX0yZMvQEKOsUvVA1gfMlqaKlz/15sfXs3xv1peRaVKZeq89BvevIcaeYqLNl8xYQ2hvybALawilFDERBOP9kVjxZz9pdptRyCKj4lp5lH2D1XtL4ENFg75ay9SpQedi9JMmkWK6ph2GiThf7/95fVBEYiqkFoP1e5ujeAxpkso+qN77hQdxN8GCAGA7j1cq0ptks/zzYBesvkJBetWEM+LOaPoweB61/fbJIDI10akCbYyGrzHqagypYdJsINrOWgNoEAG3aZO0zFHSzWJjTEtytwS/98v7t6xhPhuFb/0sMMWepwXIekU44im+57/Cn++c/MqlwJILlSmup80tmWXvN2j2+snHZvOr/MOvWNXLN5gykr29XvIBPWR0dzozNz4Apruo8KP6DMTRwCN1j6/tDA2Ir+K28S2rUKdoVdH38LgAL8epaFJ8iNbiEfXyOf2i5Wmbkx/xIP18H9OC71G6U6Q=
